<?php

return [
    'slug' => 'accordion',
    'default' => (object) [
        'id' => '',
        'list' => [],
        'beforeHeading' => '',
        'afterHeading' => '',
        'beforeContent' => '<p>',
        'afterContent' => '</p>',
        'componentElement' => 'div',
        'sectionElement' => 'div',
        'sectionHeadingElement' => 'button',
        'sectionContentElement' => 'div',
        'spacedSections' => false,
        'taxonomy' => [],
        'taxonomyPosition' => '',
    ],
    'description' => [
        'id' => 'ID for the accordion',
        'list' => 'List of accordion section',
        'beforeHeading' => 'Insert before heading',
        'afterHeading' => 'Insert after heading',
        'beforeContent' => 'Insert before content',
        'afterContent' => 'Insert after content',
        'componentElement' => 'Component element',
        'sectionElement' => 'Section element',
        'sectionHeadingElement' => 'Section heading component',
        'sectionContentElement' => 'Section content component',
        'spacedSections' => 'Sections are spaced instead of glued together',
        'taxonomy' => 'Array of taxonomies such as tags',
        'taxonomyPosition' => 'Taxonomy position like top or below',
    ],
    'types' => [
        'id' => 'string',
        'list' => 'array',
        'beforeHeading' => 'string',
        'afterHeading' => 'string',
        'beforeContent' => 'string',
        'afterContent' => 'string',
        'componentElement' => 'string',
        'sectionElement' => 'string',
        'sectionHeadingElement' => 'string',
        'sectionContentElement' => 'string',
        'spacedSections' => 'bool',
        'taxonomy' => 'array',
        'taxonomyPosition' => 'string',
    ],
    'view' => 'accordion.blade.php',
    'dependency' => [
        'sass' => [
            'components' => [
                'accordion',
                'icon',
                'tags',
            ],
        ],
    ],
];
