<?php

return [
    'slug' => 'button',
    'default' => (object) [
        'text' => false,
        'size' => 'md',
        'color' => 'default',
        'type' => 'button',
        'style' => 'filled',
        'shape' => 'normal',
        'href' => false,
        'target' => '_top',
        'componentElement' => 'button',
        'labelElement' => 'span',
        'ripple' => true,
        'pressed' => 'false',
        'toggle' => false,
        'icon' => false,
        'reversePositions' => false,
        'fullWidth' => false,
        'classListIcon' => [],
        'classListText' => [],
        'ariaLabel' => '',
        'disableColor' => true,
    ],
    'description' => [
        'label' => 'The label of the button.',
        'href' => 'Where should the button link to?',
        'target' => 'Open a new tab or not?',
        'componentElement' => 'The tag to use for this component.',
        'labelElement' => 'The element containing the label.',
        'ripple' => 'Enable / disable ripple on click.',
        'text' => 'The text-content of a button.',
        'icon' => 'The name of the icon.',
        'color' => 'The color scheme for the button.',
        'size' => 'The size of the button; sm, md, lg.',
        'toggle' => 'Will toggle the color of the font.',
        'type' => 'What button type.',
        'style' => 'The type of appearance, can be basic, filled or outlined.',
        'shape' => 'If the shape of the button should be normal, or fully rounded (pill style).',
        'reversePositions' => 'Reverse the position of icon and text.',
        'fullWidth' => 'Makes button full width.',
        'classListIcon' => 'Array of classes placed on the icon',
        'classListText' => 'Array of classes placed on the text',
        'ariaLabel' => 'Aria label text for the button',
        'disableColor' => 'To use or not to use the disabled color even if the button is disabled',
    ],
    'types' => [
        'text' => 'string',
        'size' => 'string',
        'color' => 'string',
        'type' => 'string',
        'style' => 'string',
        'shape' => 'string',
        'href' => 'string|NULL',
        'target' => 'string',
        'componentElement' => 'string',
        'labelElement' => 'string',
        'ripple' => 'boolean',
        'pressed' => 'string',
        'toggle' => 'boolean',
        'icon' => 'string',
        'reversePositions' => 'boolean',
        'fullWidth' => 'boolean',
        'classListIcon' => 'array',
        'classListText' => 'array',
        'ariaLabel' => 'string',
        'disableColor' => 'boolean',
    ],
    'view' => 'button.blade.php',
    'dependency' => [
        'sass' => [
            'components' => [
                'button',
                'icon',
            ],
        ],
    ],
];
