<?php

namespace ComponentLibrary\Component\Accordion__item;

/**
 * Class Accordion
 * @package ComponentLibrary\Component\Accordion
 */
class Accordion__item extends \ComponentLibrary\Component\BaseController implements Accordion__itemInterface
{
    private $heading;

    public function init() {
        //Extract array for eazy access (fetch only)
        extract($this->data);

        $this->data['baseClass'] = 'c-accordion';
        $this->data['classList'][] = 'c-accordion__section';
        $this->data['id'] = $this->sanitizeIdAttribute(uniqid());

        $this->data['headingType']  = $this->headingType($this->heading) ? $this->data['baseClass'] . '__heading-is-array' : '';
        $this->data['ariaLabel']    = $this->headingType($this->heading) ? $this->heading[0] : $this->heading;

        //Removes duplicate baseclass (Autogenerated)
        if (function_exists('add_filter')) {
            add_filter('ComponentLibrary/Component/Accordion__item/Class', function ($class, $context) {
                return array_diff($class, ['c-accordion']);
            }, 10, 3);
        }
    }

    private function headingType($heading) {
        return !empty($heading) && is_array($heading);
    }
    // -------------------------------------------------------------------------
    // ComponentInterface — generated getters
    // -------------------------------------------------------------------------

    public function getSlug(): string
    {
        return 'accordion__item';
    }

    // -------------------------------------------------------------------------
    // Accordion__itemInterface — generated getters
    // -------------------------------------------------------------------------

    public function getId(): string
    {
        return $this->data['id'] ?? '';
    }

    public function getHeading(): string|array
    {
        return $this->data['heading'] ?? '';
    }

    public function getBeforeHeading(): string
    {
        return $this->data['beforeHeading'] ?? '';
    }

    public function getAfterHeading(): string
    {
        return $this->data['afterHeading'] ?? '';
    }

    public function getBeforeContent(): string
    {
        return $this->data['beforeContent'] ?? '';
    }

    public function getAfterContent(): string
    {
        return $this->data['afterContent'] ?? '';
    }

    public function getSectionElement(): string
    {
        return $this->data['sectionElement'] ?? 'div';
    }

    public function getSectionHeadingElement(): string
    {
        return $this->data['sectionHeadingElement'] ?? 'a';
    }

    public function getSectionContentElement(): string
    {
        return $this->data['sectionContentElement'] ?? 'div';
    }

    public function getTaxonomy(): array
    {
        return $this->data['taxonomy'] ?? [];
    }

    public function getTaxonomyPosition(): string
    {
        return $this->data['taxonomyPosition'] ?? '';
    }

    public function getIcon(): string
    {
        return $this->data['icon'] ?? 'keyboard_arrow_down';
    }
}
