<?php

return [
    'slug' => 'fileinput',
    'default' => (object) [
        'description' => '',
        'name' => 'files',
        'accept' => 'audio/*,video/*,image/*',
        'multiple' => false,
        'preview' => false,
        'maxSize' => null,
        'uploadErrorMessage' => null,
        'uploadErrorMessageMinFiles' => null,
        'icon' => 'file_upload',
        'required' => false,
        'filesMax' => 1,
        'filesMin' => 0,
        'label' => '',
        'buttonLabel' => 'Select file',
        'buttonRemoveLabel' => 'Remove file',
        'buttonDropLabel' => 'Drop files here',
        'allowedFileTypesLabel' => 'Allowed files: ',
        'fileTypeVideosLabel' => 'Videos',
        'fileTypeImagesLabel' => 'Images',
        'fileTypeAudioLabel' => 'Audios',
        'maximumSizeLabel' => 'Maximum size',
    ],
    'description' => [
        'description' => 'Additional description or instructions.',
        'name' => 'files',
        'accept' => 'What file types to accept. Use MIME types. Example: audio/*,video/*,image/*',
        'multiple' => 'Allow single or multiple files',
        'uploadErrorMessage' => 'Message to show when upload fails',
        'uploadErrorMessageMinFiles' => 'Message to show when minimum number of files is not met',
        'icon' => '@link:component/icon',
        'required' => 'If field is required',
        'filesMax' => 'Maximum number of files (int). Foced to 1 if multiple is false. Default 10 for multiple.',
        'filesMin' => 'Minimum number of files (int). Default is 0.',
        'buttonDropLabel' => 'A label for the drop area',
        'maxSize' => 'Maximum file size allowed in MB. Number (int) in bytes or string (small, medium, large). Default is null (no limit).',
        'label' => 'Label to show on the field',
        'buttonLabel' => 'What text to show on the button',
        'buttonRemoveLabel' => 'What text to show on the remove button',
        'allowedFileTypesLabel' => 'Label for allowed file types',
        'fileTypeVideosLabel' => 'Label for video file types',
        'fileTypeImagesLabel' => 'Label for image file types',
        'fileTypeAudioLabel' => 'Label for audio file types',
        'maximumSizeLabel' => 'Maximum size',
    ],
    'types' => [
        'description' => 'string',
        'name' => 'string',
        'accept' => 'string',
        'multiple' => 'boolean',
        'uploadErrorMessage' => 'string',
        'uploadErrorMessageMinFiles' => 'string',
        'icon' => 'string',
        'required' => 'boolean',
        'filesMax' => 'integer',
        'filesMin' => 'integer',
        'preview' => 'boolean',
        'maxSize' => 'string|int',
        'label' => 'string',
        'buttonLabel' => 'string',
        'buttonRemoveLabel' => 'string',
        'buttonDropLabel' => 'string',
        'allowedFileTypesLabel' => 'string',
        'fileTypeVideosLabel' => 'string',
        'fileTypeImagesLabel' => 'string',
        'fileTypeAudioLabel' => 'string',
        'maximumSizeLabel' => 'string',
    ],
    'view' => 'fileinput.blade.php',
    'dependency' => [
        'sass' => [
            'components' => [
                'fileInput',
                'icon',
                'button',
            ],
        ],
    ],
];
